### ISSUE TITLE
Geolocation Functionality

### ISSUE THREAD

**Issue by als9xd** [als9xd/4bar#9]
- Integrate with store. Facebook Marketplace may give ideas.
- Nearby events notification system. Similar to Bandisintown.

**Comment by als9xd** [comment]
Integrate with store. Facebook Marketplace may give ideas.
Nearby events notification system. Similar to Bandisintown.

**Comment by rfbasden** [comment]
Map has been integrated, need to add functions for getting user current location, automatically adding pins where tournaments have been located, assuming the user has the tags.
